### ISSUE TITLE
无法查询isbn10的图书

### ISSUE THREAD

**Issue by maooyer** [fan123199/szulib#1]
校友，你好！
我最近想做一个在豆瓣上查询馆藏信息的小插件，正巧发现你已经做了，就直接拿来用了。在使用过程中发现一个问题，就是这个插件不能查询2007年以前的书，原因如下：

根据百度百科关于[ISBN](http://baike.baidu.com/view/180962.htm?fromtitle=ISBN&fromid=391662&type=syn)的描述，我国的图书在2007年以前是10位isbn码，2007年以后升级为13位。豆瓣图书的isbn码全部为13位（10位的自动转化为13位），而图书馆的则没有做转换。这种不一致造成我们无法查询到2007年以前的图书。

今天下午我本想把这个查询功能完善一下，奈何不会javascript。希望你有空能完善一下功能。

附例子：
比如这本书(http://book.douban.com/subject/1221479/) 在图书馆是存在的，
http://opac.lib.szu.edu.cn/opac/searchresult.aspx?isbn_f=7501946973  //用isbn10查询是存在的
http://opac.lib.szu.edu.cn/opac/searchresult.aspx?isbn_f=9787501946976 //用isbn13查询是不存在的

**Comment by fan123199** [comment]
你好，我的js也是入门水平，照着你的request修改了我的代码。
